---
# General and common requirement
- name: mbsec-dhcpd | Install and Configure
  include_tasks: install-configure.yml
  # DHCP is a critical infrastructure component. So, I put a double validation here. Thanks! : )
  when: inventory_hostname in groups['dhcp-servers']
...
